### ISSUE TITLE
Python Error - Selecting Plugin Settings - Windows 11

### ISSUE THREAD

**Issue by Yakwrangler** [minorua/Qgis2threejs#357] opened 2024-10-12 14:47 UTC
On selecting File > Plugin Settings produces the following Python error ... note this occurs only on WIN11, not WIN10.
Both Windows versions are running 3.34.11-Prizren and Qgis2threejs 2.7.3.
My finger trouble or is this an issue?
Brgds, Rob R

QGIS version | 3.34.11-Prizren | QGIS code revision | 2904bcec
Qt version | 5.15.13
Python version | 3.12.6
GDAL/OGR version | 3.9.2
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
Active Python plugins
Qgis2threejs | 2.7.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

An error has occurred while executing Python code: 

AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'? 
Traceback (most recent call last):
  File "C:\Users/micro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\q3dwindow.py", line 465, in pluginSettings
    dialog = SettingsDialog(self)
             ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users/micro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\Qgis2threejs\pluginsettings.py", line 47, in __init__
    parser = configparser.SafeConfigParser()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?

Python version: 3.12.6 (main, Sep  7 2024, 18:59:42) [MSC v.1938 64 bit (AMD64)] 
QGIS version: 3.34.11-Prizren Prizren, 2904bcec 

Python Path:
C:/PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python
C:/Users/micro/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/micro/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.11/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.11\apps\grass\grass84\etc\python
C:\Users\micro\Documents
C:\Program Files\QGIS 3.34.11\bin\python312.zip
C:\PROGRA~1\QGIS33~1.11\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib
C:\Program Files\QGIS 3.34.11\bin
C:\PROGRA~1\QGIS33~1.11\apps\Python312
C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.11\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/micro/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/micro/Documents/GIS DataBase/2024_Maps

**Comment by minorua** [comment] 2024-10-12 23:36
Duplicate of #345.

Thank you for your feedback!

**Closed by minorua** 2024-10-12 23:36 UTC
Labels: duplicate
